TRUNCATE educational_plan RESTART IDENTITY CASCADE;
--
TRUNCATE t_group RESTART IDENTITY CASCADE;
--
TRUNCATE student RESTART IDENTITY CASCADE;
--
TRUNCATE academic_performance RESTART IDENTITY CASCADE;




